name: CI-CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# dddddsfsdf
jobs:
  simple-ci:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Install frontend dependencies
         working-directory: ../../frontend
         run: npm install
    
     - name: Install backend dependencies
         working-directory: ../../backend 
         run: npm install

     - name: Run npm audit (frontend)
        run: npm audit --audit-level=moderate
 
     - name: Run npm audit (backend)
        working-directory: backend
        run: npm audit --audit-level=moderate
      
